### ISSUE TITLE
Retaining comments

### ISSUE THREAD

**Issue by colelawrence** [heyimalex/wafu#3]
Hi @heyimalex !

I came across your package after it was posted on /r/rust. Thank you for putting in the time to make this. I'm really excited to be able to use it in a simple Language Server implementation I'm working on.

I noticed that the declaration typings that come with the library are having their documentation stripped because of the use of `//` comments as opposed to docstring comments in the form `/** docstring */`

Would you accept some help converting that documentation to docstrings so they are retained in the `.d.ts` files?

Read more about TypeScript's doc expectations here: https://github.com/microsoft/tsdoc

Thanks,

Cole

**Comment by heyimalex** [comment]
Hey, thanks! I didn't know about tsdoc and always kinda wondered why all the typescript library code I read was formatted like that.

Re: Using wafu in anything else, I'm not sure I would recommend that :') Like the readme says, this is a _drop in_ replacement for fuse, but after going through the fuse source I'm not sure that fuse is a very good search library. I _want_ to make something better, but I think that it would be a large undertaking.

But in any case, thanks for the pr, I'll push a new version when I get home tonight!
